bwa: /home/qcb-panasas/kaliappa/code/bwa/bwa-0.7.17/bwa
ref: /home/qcb-panasas/kaliappa/data/hg19/bwa/hg19.fa

chromSizes: 
  /home/qcb-panasas/kaliappa/code/smurfseq_scripts/data/hg19.chrom.sizes
binBounds: 
  /home/qcb-panasas/kaliappa/code/smurfseq_scripts/data/bins_5k_hg19.bed
gc: 
  /home/qcb-panasas/kaliappa/code/smurfseq_scripts/data/bins_5k_hg19_gc.txt
badBins: 
  /home/qcb-panasas/kaliappa/code/smurfseq_scripts/data/bins_5k_hg19_exclude.txt
binCounts:
  /home/qcb-panasas/kaliappa/code/smurfseq_scripts/scripts/getBinCounts.py
cbs:
  /home/qcb-panasas/kaliappa/code/smurfseq_scripts/scripts/cnvAnalysis.R

samples:
  - hg19_cn2
  - hg19_p_cn1
  - hg19_p_cn4
  - hg19_q_cn1
  - hg19_q_cn4
  - hg19_chr1-5_cn1
  - hg19_chr1-5_cn3
  - hg19_chr1-5_cn4
  - hg19_chr1-3_cn1
  - hg19_chr1-3_cn3
  - hg19_chr1-3_cn4
