## Read names
read1Suffix: _R1_001.fastq.gz
read2Suffix: _R2_001.fastq.gz

## Input/output dirs
readsDir: /scratch2/kaliappa/cnv/chla_mm/reads
fastqcDir: /scratch2/kaliappa/cnv/chla_mm/mm_map/fastqc
mappedDir: /scratch2/kaliappa/cnv/chla_mm/mm_map/mapped_reads
flagstatDir: /scratch2/kaliappa/cnv/chla_mm/mm_map/flagstat
insertSzDir: /scratch2/kaliappa/cnv/chla_mm/mm_map/insert_sz
countsDir: /scratch2/kaliappa/cnv/chla_mm/mm_map/bin_counts
cnvDir: /scratch2/kaliappa/cnv/chla_mm/mm_map/cnv
logDir: /scratch2/kaliappa/cnv/chla_mm/mm_map/logs
tmpDir: /scratch2/kaliappa/cnv/chla_mm/mm_map/tmpdir

## Tools
bwa: /scratch2/kaliappa/tools/bwa/bwa-0.7.17/bwa
picard: /scratch2/kaliappa/tools/picard/picard.jar
binCounts: /scratch2/kaliappa/cnv/CNVPipeline/scripts/getBinCounts.py
cnvSeg: /scratch2/kaliappa/cnv/CNVPipeline/scripts/cnvProfile.R
preseq: /project/kaliappa_550/rish/tools/preseq/preseq_install/bin/preseq 
plotLcCurve: /project/kaliappa_550/rish/methyl/bs_utils/scripts/lcExtraPlot.R

## Tool parameters
nThreads: 16
minMapq: 30

preseqStep: 100000
preseqExtrap: 100000000

## Data
# ref: /scratch2/kaliappa/tools/bwa/hg19/hg19.fa
ref: /project/kaliappa_550/rish/references/mm10/mm10.fa

dzBed: /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz_enc/hg19_150bp_dz_enc.bed

binBounds5k: /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz_enc/hg19_5k_gz_enc_bins.bed
binBounds20k: /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz_enc/hg19_20k_gz_enc_bins.bed

gc5k: /scratch2/kaliappa/cnv/scrpts_test/hg19_5k_gz_enc_gc.bed
gc20k: /scratch2/kaliappa/cnv/scrpts_test/hg19_20k_gz_enc_gc.bed

badBins5k: /scratch2/kaliappa/cnv/cnv_bounds/bad_bins/new_scripts/hg19_5k_gz_enc_badbind.bed
badBins20k: /scratch2/kaliappa/cnv/cnv_bounds/bad_bins/new_scripts/hg19_20k_gz_enc_badbind.bed
