## Read names
read1Suffix: _1.fastq.gz
read2Suffix: _2.fastq.gz

## Input/output dirs
readsDir: /project/kaliappa_550/rish/wga/pta/reads
fastqcDir: /project/kaliappa_550/rish/wga/pta/fastqc
mappedDir: /project/kaliappa_550/rish/wga/pta/mapped_reads
flagstatDir: /project/kaliappa_550/rish/wga/pta/flagstat
insertSzDir: /project/kaliappa_550/rish/wga/pta/insert_sz
countsDir: /project/kaliappa_550/rish/wga/pta/bin_counts
cnvDir: /project/kaliappa_550/rish/wga/pta/cnv
logDir: /project/kaliappa_550/rish/wga/pta/logs
tmpDir: /project/kaliappa_550/rish/wga/pta/tmpdir

## Tools
bwa: /scratch2/kaliappa/tools/bwa/bwa-0.7.17/bwa
picard: /scratch2/kaliappa/tools/picard/picard.jar
binCounts: /scratch2/kaliappa/cnv/CNVPipeline/scripts/getBinCounts.py
cnvSeg: /scratch2/kaliappa/cnv/CNVPipeline/scripts/cnvProfile.R

## Tool parameters
nThreads: 16
minMapq: 30

## Data
ref: /scratch2/kaliappa/tools/bwa/hg19/hg19.fa

dzBed: /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz_enc/hg19_150bp_dz_enc.bed

binBounds5k: /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz_enc/hg19_5k_gz_enc_bins.bed
binBounds20k: /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz_enc/hg19_20k_gz_enc_bins.bed

gc5k: /scratch2/kaliappa/cnv/scrpts_test/hg19_5k_gz_enc_gc.bed
gc20k: /scratch2/kaliappa/cnv/scrpts_test/hg19_20k_gz_enc_gc.bed

badBins5k: /scratch2/kaliappa/cnv/cnv_bounds/bad_bins/new_scripts/hg19_5k_gz_enc_badbind.bed
badBins20k: /scratch2/kaliappa/cnv/cnv_bounds/bad_bins/new_scripts/hg19_20k_gz_enc_badbind.bed
