## Read names
read1Suffix: _R1_001.fastq.gz
read2Suffix: _R2_001.fastq.gz

## Input/output dirs
readsDir: /scratch2/kaliappa/cnv/cnv_bounds/snake_test/reads
fastqcDir: /scratch2/kaliappa/cnv/cnv_bounds/snake_test/fastqc
mappedDir: /scratch2/kaliappa/cnv/cnv_bounds/snake_test/mapped_reads
flagstatDir: /scratch2/kaliappa/cnv/cnv_bounds/snake_test/flagstat
insertSzDir: /scratch2/kaliappa/cnv/cnv_bounds/snake_test/insert_sz
countsDir: /scratch2/kaliappa/cnv/cnv_bounds/snake_test/bin_counts
cnvDir: /scratch2/kaliappa/cnv/cnv_bounds/snake_test/cnv
logDir: /scratch2/kaliappa/cnv/cnv_bounds/snake_test/logs

## Tools
bwa: /scratch2/kaliappa/tools/bwa/bwa-0.7.17/bwa
picard: /scratch2/kaliappa/tools/picard/picard.jar
binCounts: /scratch2/kaliappa/cnv/CNVPipeline/scripts/getBinCounts.py
cnvSeg: /scratch2/kaliappa/cnv/CNVPipeline/scripts/cnvProfile.R

## Tool parameters
nThreads: 16
minMapq: 30

## Data
ref: /scratch2/kaliappa/tools/bwa/hg19/hg19.fa

dzBed: /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz_enc/hg19_150bp_dz_enc.bed

binBounds5k: /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz_enc/hg19_5k_gz_enc_bins.bed
binBounds20k: /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz_enc/hg19_20k_gz_enc_bins.bed

gc5k: /scratch2/kaliappa/cnv/scrpts_test/hg19_5k_gz_enc_gc.bed
gc20k: /scratch2/kaliappa/cnv/scrpts_test/hg19_20k_gz_enc_gc.bed

badBins5k: /scratch2/kaliappa/cnv/cnv_bounds/bad_bins/wbc_5k_badbins.bed
badBins20k: /scratch2/kaliappa/cnv/cnv_bounds/bad_bins/wbc_20k_badbins.bed
