readsDir: /scratch2/kaliappa/cnv/cnv_bounds/usc_um/reads
read1Suffix: _R1_001.fastq.gz
read2Suffix: _R2_001.fastq.gz

bwa: /scratch2/kaliappa/tools/bwa/bwa-0.7.17/bwa
ref: /scratch2/kaliappa/tools/bwa/hg19/hg19.fa

nThreads: 16

minMapq: 30

picard: /scratch2/kaliappa/tools/picard/picard.jar

filterDz:
  /scratch2/kaliappa/cnv/cna_utils/bin_bounds/filterDeadzone.py
dzBed:
#  /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz_dac_enc/hg19_150bp_dz_dac_enc.bed
  /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz_enc/hg19_150bp_dz_enc.bed
#  /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz_dac/hg19_150bp_dz_dac.bed
#  /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz/hg19_150bp_dz.bed

chromSizes:
  /scratch2/kaliappa/cfdna/cfDNA_utils/data/hg19.chrom.sizes
binCounts:
  /scratch2/kaliappa/cfdna/cfDNA_utils/scripts/getBinCounts.py
cbs:
  /scratch2/kaliappa/cnv/cna_utils/bin_bounds/cnvAnalysis.R
cbsNoBad:
  /scratch2/kaliappa/cnv/cna_utils/bin_bounds/cnvAnalysisNoBadBins.R

oldBinBounds5k:
  /scratch2/kaliappa/cfdna/cfDNA_utils/data/bins_5k_hg19.bed
oldGc5k:
  /scratch2/kaliappa/cfdna/cfDNA_utils/data/bins_5k_hg19_gc.txt
oldBinBounds20k:
  /scratch2/kaliappa/cfdna/cfDNA_utils/data/bins_20k_hg19.bed
oldGc20k:
  /scratch2/kaliappa/cfdna/cfDNA_utils/data/bins_20k_hg19_gc.txt

newBinBounds5k:
#  /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz_dac_enc/hg19_5k_gz_dac_enc_bins.bed
  /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz_enc/hg19_5k_gz_enc_bins.bed
#  /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz_dac/hg19_5k_gz_dac_bins.bed
#  /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz/hg19_5k_gz_bins.bed
#  /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/bwa/hg19_5k_bin_bounds.bed
newGc5k:
#  /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz_dac_enc/hg19_5k_gz_dac_enc_gc.bed
  /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz_enc/hg19_5k_gz_enc_gc.bed
#  /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz_dac/hg19_5k_gz_dac_gc.bed
#  /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz/hg19_5k_gz_gc.bed
#  /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/bwa/hg19_5k_gc.bed
newBinBounds20k:
#  /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz_dac_enc/hg19_20k_gz_dac_enc_bins.bed
  /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz_enc/hg19_20k_gz_enc_bins.bed
#  /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz_dac/hg19_20k_gz_dac_bins.bed
#  /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz/hg19_20k_gz_bins.bed
#  /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/bwa/hg19_20k_bin_bounds.bed
newGc20k:
#  /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz_dac_enc/hg19_20k_gz_dac_enc_gc.bed
  /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz_enc/hg19_20k_gz_enc_gc.bed
#  /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz_dac/hg19_20k_gz_dac_gc.bed
#  /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/gz/hg19_20k_gz_gc.bed
#  /scratch2/kaliappa/cnv/cnv_bounds/genome_reads/boundaries/bin_bounds_150bp/bwa/hg19_20k_gc.bed

badBins5k:
  /scratch2/kaliappa/cnv/cnv_bounds/bad_bins/cfdna_5k_badbins.txt
#   /scratch2/kaliappa/cnv/cnv_bounds/bad_bins/tlp_5k_badbins.txt
#   /scratch2/kaliappa/cnv/cnv_bounds/bad_bins/cfdna_5k_fifth_badbins.txt
#   /scratch2/kaliappa/cnv/cnv_bounds/bad_bins/wbc_5k_fifth_badbins.txt
#   /scratch2/kaliappa/cnv/cnv_bounds/bad_bins/wbc_5k_badbins.txt
badBins20k:
  /scratch2/kaliappa/cnv/cnv_bounds/bad_bins/cfdna_20k_badbins.txt
#   /scratch2/kaliappa/cnv/cnv_bounds/bad_bins/tlp_20k_badbins.txt
#   /scratch2/kaliappa/cnv/cnv_bounds/bad_bins/cfdna_20k_fifth_badbins.txt
#   /scratch2/kaliappa/cnv/cnv_bounds/bad_bins/wbc_20k_fifth_badbins.txt
#   /scratch2/kaliappa/cnv/cnv_bounds/bad_bins/wbc_20k_badbins.txt
